gripper:
  type: effort_controllers/JointTrajectoryController
  joints:
    - finger_joint1
  gains:
    finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

      # запустить рос контрол!!